### ISSUE TITLE
LOGO KONKURRANSE

### ISSUE THREAD

**Issue by jhannes** [kristiania-pg6301-2023/pg6301-frontend-programming#1]
Vi trenger LOGO for kurset! Jeg tenker vi skal gjøre det demokratisk og jeg ser overhode ingen mulighet for at jeg vil angre på det.

Svar på denne ISSUEN med en kommentar med et forslag til logo, eller gi en stemme til et annet forslag med EMOJIs. Forslaget med flest stemmer blir kursets logo, uansett hvor useriøst eller stygt det er.

**Comment by eajohansen** [comment]
![webutvikling-og-api-design-logo](https://github.com/kristiania-pg6301-2023/pg6301-frontend-programming/assets/29361988/e2184c78-bc6b-4d2f-b11d-f893c0bf8e2d)

**Comment by Stefannaeve** [comment]
<img width="768" alt="Cursed" src="https://github.com/kristiania-pg6301-2023/pg6301-frontend-programming/assets/114489609/35b268d6-4de3-4c6f-ae99-55470996dbc2">

**Comment by Svendzen** [comment]
![logo-konkuranse](https://github.com/kristiania-pg6301-2023/pg6301-frontend-programming/assets/44970661/44dfc36e-d70c-4da1-aaa9-48a8863b4591)
